POST / HTTP/1.1
connection: keep-alive
Content-Type: multipart/form-data; boundary=---------------------------735323031399963166993862150
Content-Length: 834

-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="text1"

text default
-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="text2"

aωb
-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="file1"; filename="a.txt"
Content-Type: text/plain

Content of a.txt.
-----------------------------735323031399963166993862150--

###############################################################

GET http://localhost:8081


###
POST /echo/post/form HTTP/1.1
Host: reqbin.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 23
      
key1=value1&key2=value2

netcat ip port
Content-Disposition: form-data; name="file"; filename="script.sh"
Content-Type: application/x-shellscript

export REQUEST_METHOD=GET
export SCRIPT_NAME=www/query_string.php 
export SERVER_PROTOCOL=HTTP/1.1 
export GATEWAY_INTERFACE=CGI/1.1 
export PATH_INFO=/query_string.php
export REQUEST_URI=/query_string.php
export PATH_TRANSLATED=www/query_string.php 
export QUERY_STRING="last_name=test" 
export SCRIPT_FILENAME=www/query_string.php
export CONTENT_TYPE="text/html" 
export CONTENT_LENGTH=392
echo "last_name=test" | ./ubuntu_cgi_tester
Content-Disposition: form-data; name="file"; filename="script.sh"
Content-Type: application/x-shellscript

export REQUEST_METHOD=GET
export SCRIPT_NAME=www/query_string.php 
export SERVER_PROTOCOL=HTTP/1.1 
export GATEWAY_INTERFACE=CGI/1.1 
export PATH_INFO=/query_string.php
export REQUEST_URI=/query_string.php
export PATH_TRANSLATED=www/query_string.php 
export QUERY_STRING="last_name=test" 
export SCRIPT_FILENAME=www/query_string.php
export CONTENT_TYPE="text/html" 
export CONTENT_LENGTH=392
echo "last_name=test" | ./ubuntu_cgi_tester